### PR TITLE
Add composer.json

### PR DESCRIPTION
**Pull request by tucksaun**

### CODE REVIEW

**Comment by joelgaujard-smartgp** [comment]
This is a must have for this project. Please @tucksaun can you check it and merge this PR in your project ?

**Comment by tucksaun** [comment]
I'm not sure to understand what you mean @joelgaujard-smartgp: this PR comes from my project. Maybe you wanted to mention @andyps instead?

**Comment by joelgaujard-smartgp** [comment]
Yes @tucksaun you are right. Sorry to bother you.
Please @andyps can you merge this PR ?

**Comment by andyps** [comment]
@joelgaujard-smartgp merged (sorry for the delay)

**Pull request merged**
